### ISSUE TITLE
Web-bluetooth-dfu stabilizing, more testing

### ISSUE THREAD

**Issue by JOSE-Sendance** [sendance/web-bluetooth-dfu#1]
**Current situation**
Unsecure npm vulnerabilities, no linting
Maybe some bugs

**Goal**
More stable

**Execution**
Cleanup (npm vulnerabilities, linting)
More testing
Make it possible to update when uC is already in bootloader

**Comment by CSC-Sendance** [comment]
Ideas:
- as (internally published/distributed?) npm package?
- as referenced "sub-git-repository" ?

@JOSE-Sendance will coordinate with @MAN-Sendance

**Comment by JOSE-Sendance** [comment]
Will not be integrated into ble-debugger-js
Changed this issue to make it more stable

**Comment by JOSE-Sendance** [comment]
![Image](https://github.com/sendance/web-bluetooth-dfu/assets/114486666/7a36a15a-25be-4b26-bae5-fb72d8b9cb53)
![Image](https://github.com/sendance/web-bluetooth-dfu/assets/114486666/2b52385c-2b3f-4efd-9715-eea3e90864e1)
This error happens but stills works, maybe find out why

**Comment by JOSE-Sendance** [comment]
Sometimes the device needs to be unpaired in windows so that it can get into bootloader??
Also if the device was already connected and not disconnected properly, it needs to be disconnected/unpaired first.

**Comment by CSC-Sendance** [comment]
> Sometimes the device needs to be unpaired in windows so that it can get into bootloader?? Also if the device was already connected and not disconnected properly, it needs to be disconnected/unpaired first.

hmm, maybe:

- pairing information is (sometimes) not persisted correctly so the info check fails?
- pairing information changes (device id / mac address etc.) during the process but is not persisted when not disconnecting properly?

**Comment by CSC-Sendance** [comment]
@JOSE-Sendance is this still relevant / open? 

If there is still something to do, we may want to postpone this until a frontend client-implementation?

**Comment by JOSE-Sendance** [comment]
Yes for now it is working, but not secure (npm vulnerability warnings). 

Yes sure this would be good.

**Comment by CSC-Sendance** [comment]
ok, let's close this then as postponed.
